name: 'BUSL Blocker'
description: 'BUSL Blocker'
inputs:
  path:
    description: 'Path to the source code to check'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: goph/licensei
    - run: make build
      shell: bash
    - run: ./install.sh
      shell: bash
    - run: ./bin/licensei check ${{ inputs.path }}
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
