name: 'BUSL Blocker'
description: 'BUSL Blocker'
inputs:
  module-path:
    description: 'Path to the go module you want to test'
    required: true
  ignore-modules:
    description: 'Comma separated list of modules to ignore'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - run: go install github.com/pulumi/go-licenses@ec48b64
      shell: bash
    - run: |
        cd "${{ inputs.module-path }}"
        go-licenses check ./... --ignore $(go list -m)
        --ignore "${{ inputs.ignore-modules }}}}"

      shell: bash
