name: 'BUSL Blocker'
description: 'BUSL Blocker'
inputs:
  path:
    description: 'Path to the source code to check'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: https://github.com/kmosher/licensei
    - run: make build
    - run: install.sh
    - run: ./bin/licensei ${{ inputs.path }}
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
